run:
    timeout: 10m
    skip-dirs:
        - pkg/pb
    skip-files:
        - internal/api/static.go
    modules-download-mode: readonly
linters-settings:
    golint:
        min-confidence: 0
linters:
    fast: true
    enable-all: true
    disable:
      - dupl
      - funlen
      - gci
      - gocognit
      - goconst
      - godox
      - gomnd
      - nolintlint
      - scopelint
      - tagliatelle
      - testpackage
